- name: Download spotify key
  get_url:
    url: https://download.spotify.com/debian/pubkey.gpg
    dest: /tmp/spotify.gpg
    mode: '0440'

- name: Add Apt signing key to keyring
  apt_key:
    id: 1C24DEFC50A757AD3544731ACC648004479BF6FA
    file: /tmp/spotify.gpg
    state: present

- apt_repository:
    repo: deb http://repository.spotify.com stable non-free 
    state: present
    filename: spotify

- apt_repository: 
    repo: 'ppa:lutris-team/lutris'

- name: Upgrade apt
  apt: upgrade=yes
  when: package_upgrade
  become: yes
  become_user: root
  become_method: sudo

- name: Install apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ packages_apt }}"

- name: Install deb packages
  apt:
    deb: "{{ item }}"
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ packages_deb }}"

- name: Remove apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: absent
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ remove_packages }}"
