- name: Add an Apt signing key, uses whichever key is at the URL
    apt_key:
      url: https://download.spotify.com/debian/pubkey.gpg
      state: present

- apt_repository:
    repo: deb http://repository.spotify.com stable non-free 
    state: present
    filename: spotify

- apt_repository: 
    repo: 'ppa:lutris-team/lutris'

- name: Upgrade apt
  apt: upgrade=yes
  when: package_upgrade
  become: yes
  become_user: root
  become_method: sudo

- name: Install apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ packages_apt }}"

- name: Install deb packages
  apt:
    deb: "{{ item }}"
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ packages_deb }}"

- name: Remove apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: absent
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ remove_packages }}"
