- name: Add an Apt signing key, will not download if present
  become: yes
  become_user: root
  become_method: sudo
  ansible.builtin.apt_key:
    id: "{{ item.id }}" 
    url: "{{ item.url }}"
    state: present
  loop: "{{ apt_key }}"

- name: Add specified repository into sources list using specified filename
  become: yes
  become_user: root
  become_method: sudo
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}" 
    state: present
    filename: "{{ item.file }}"
  loop: "{{ apt_repository }}"

- name: Upgrade apt
  apt: upgrade=yes
  when: package_upgrade
  become: yes
  become_user: root
  become_method: sudo

- name: Install apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ packages_apt }}"

- name: Install deb packages
  apt:
    deb: "{{ item }}"
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ packages_deb }}"

  #- name: Remove apt packages
  #  apt:
  #    name: "{{ item }}"
  #    update_cache: yes
  #    state: absent
  #  become: yes
  #  become_user: root
  #  become_method: sudo
  #  loop: "{{ remove_packages }}"
