- name: Create font directory if it does not exist
  file:
    path: "{{ dotfiles_user_home }}/.fonts"
    state: directory
    mode: '0755'

- name: install fonts
  unarchive:
    src: https://github.com/IBM/plex/releases/latest/download/TrueType.zip
    dest: "{{ dotfiles_user_home }}/.fonts"
    remote_src: yes
